server:
  port: 9000

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "http://localhost:4200"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
        - id: planeacion
          uri: lb://planeacion
          predicates:            
            - Path= /api/carrera/**, 
                    /api/grupo/**, 
                    /api/feriado/**,
                    /api/horario/**,
                    /api/materia/**,
                    /api/parcial/**,
                    /api/periodo/**,
                    /api/vacacion/**          
          filters:
            - RewritePath=/(?<path>.*), /$\{path}
            
eureka:
  client: 
    service-url:
      defaultZone: http://localhost:8761/eureka/